version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
      - "8081:8081" 
    environment:
      ASPNETCORE_URLS: "https://+;http://+" 
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "tbd" 
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx 
    volumes:
      # Optional: Mount local code for development (if needed)
      # - ../backend:/source # Mounts local backend code into the container
      # Optional: Volume for HTTPS dev certificate
      # - ~/.aspnet/https:/https/:ro # Mounts local dev certs (adjust path as needed)
    networks:
      - splitey-net

  # Placeholder for the database service (MySQL)
  # db:
  #   image: mysql:8.0
  #   container_name: splitey-db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mysql_root_password 
  #     MYSQL_DATABASE: splitey_db
  #     MYSQL_USER: splitey_user
  #     MYSQL_PASSWORD: mysql_user_password 
  #   ports:
  #     - "3306:3306" 
  #   volumes:
  #     - splitey-db-data:/var/lib/mysql 
  #   networks:
  #     - splitey-net

networks:
  splitey-net:
    driver: bridge

# volumes:
#   splitey-db-data: 
