# Generated by Django 5.2 on 2025-04-19 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_friendship_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensegroup",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="expensegroup",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="friendship",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendship",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
