# Generated by Django 5.2 on 2025-04-19 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="splitrelationship",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="splitrelationship",
            name="owed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="split_owed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="splitrelationship",
            name="owes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="split_owes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
