# Generated by Django 5.2 on 2025-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_splitrelationship_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="splitrelationship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
